export const faqs = [
  {title: 'What is xBid?', description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatibus architecto amet ratione rerum, quis distinctio minus rem optio molestias adipisci eligendi! Necessitatibus maxime optio doloribus, saepe et quaerat dolor harum!'},
  {title: 'What does "starting price" mean in auctions?', description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatibus architecto amet ratione rerum, quis distinctio minus rem optio molestias adipisci eligendi! Necessitatibus maxime optio doloribus, saepe et quaerat dolor harum!'},
  {title: 'How does the price increment system work in auctions?', description: 'In auctions, the price increment system determines the minimum increase required for each bid. It promotes fairness and competition, with the increment usually set by the auctioneer or platform. It can be a fixed amount or a percentage of the current bid, encouraging meaningful bids and raising the final price.'},
  {title: 'What is the maximum amount the auction can reach?', description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatibus architecto amet ratione rerum, quis distinctio minus rem optio molestias adipisci eligendi! Necessitatibus maxime optio doloribus, saepe et quaerat dolor harum!'},
  {title: 'What is the duration of the auction?', description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatibus architecto amet ratione rerum, quis distinctio minus rem optio molestias adipisci eligendi! Necessitatibus maxime optio doloribus, saepe et quaerat dolor harum!'},
  {title: 'What happens if there are no bids placed during the 60-second period?', description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatibus architecto amet ratione rerum, quis distinctio minus rem optio molestias adipisci eligendi! Necessitatibus maxime optio doloribus, saepe et quaerat dolor harum!'},
  {title: 'What happens if someone bids more than the amount I bid?', description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatibus architecto amet ratione rerum, quis distinctio minus rem optio molestias adipisci eligendi! Necessitatibus maxime optio doloribus, saepe et quaerat dolor harum!'},
  {title: 'Is it possible to retrieve the bid amount if my bid is surpassed, and I decide not to continue bidding?', description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatibus architecto amet ratione rerum, quis distinctio minus rem optio molestias adipisci eligendi! Necessitatibus maxime optio doloribus, saepe et quaerat dolor harum!'},
]